<?php
/*******************************************
** finds a specific order based of the id **
********************************************/

function generate_order_no(){

//include file to connect to the database
include_once '../../database/connectdb.php';



//include file to check errors in sql statements
include_once '../../database/error_check.php';

  //prepare and bind sql statement
  //inner join the customer accounts table into the orders table in order to get the customer's name using the customer id as the key
  $stmt_order_no = $conn->prepare("SELECT Order_No FROM Orders
                                   ORDER BY Order_Id DESC
                                   LIMIT 1");

  //execute the prepared statement
  $stmt_order_no->execute();

  //store the selected result
  $stmt_order_no->store_result();

  //bind the selected results
  $stmt_order_no->bind_result($order_noRow);
  
  //value for the autogenerated order number
  $next_order_no = 0;
  
  if ($stmt_order_no->num_rows > 0){
    while ($stmt_order_no->fetch()){
    
      //add one to the previous order number
      $next_order_no = $order_noRow + 1;
    }
    
  //if there are no orders in the database
  } else {
    $next_order_no = 100000;
  }
  
  //close the statement
  $stmt_order_no->close();
  
  return $next_order_no;
}
